#include "P18F458.INC"


	processor 18F458


;Configuration Byte 4L Options
_DEBUG_ON_4L      EQU  H'7F'    ; Enabled
_DEBUG_OFF_4L     EQU  H'FF'    ; Disabled

_LVP_ON_4L        EQU  H'FF'    ; Enableda
_LVP_OFF_4L       EQU  H'FB'    ; Disabled

; Configurazione bit
	__CONFIG	_CONFIG1H, _OSCS_OFF_1H & _HS_OSC_1H
	__CONFIG	_CONFIG2L, _BOR_ON_2L & _BORV_27_2L & _PWRT_ON_2L

;#DEFINE DEBUG
;	IFDEF DEBUG
;DEGUG
	__CONFIG	_CONFIG2H, _WDT_OFF_2H & _WDTPS_128_2H
	__CONFIG	_CONFIG4L, _DEBUG_ON_4L & _LVP_OFF_4L & _STVR_ON_4L
	__CONFIG	_CONFIG5L, H'FF'
	__CONFIG	_CONFIG5H, H'FF'
	__CONFIG	_CONFIG6L, H'FF'
	__CONFIG	_CONFIG6H, H'FF'
	__CONFIG	_CONFIG7L, H'FF'
	__CONFIG	_CONFIG7H, H'FF'
;	ELSE
;NO DEGUG
;	__CONFIG	_CONFIG2H, _WDT_ON_2H & _WDTPS_128_2H
;	__CONFIG	_CONFIG4L, _DEBUG_OFF_4L & _LVP_OFF_4L & _STVR_ON_4L
;	__CONFIG	_CONFIG5L, 0		;code protect
;	__CONFIG	_CONFIG5H, 0
;	__CONFIG	_CONFIG6L, 0
;	__CONFIG	_CONFIG6H, 0
;	__CONFIG	_CONFIG7L, 0		;table read protect
;	__CONFIG	_CONFIG7H, 0
;	ENDIF


;00000000000000000000000000000000000
;	__CONFIG	_CONFIG1H,	_OSCS_OFF_1H & _HS_OSC_1H
;	__CONFIG	_CONFIG2L,	_BOR_ON_2L & _PWRT_ON_2L & _BORV_25_2L
;	__CONFIG	_CONFIG2H,	_WDT_ON_2H & _WDTPS_128_2H &
;	__CONFIG	_CONFIG4L,
;	__CONFIG	_CONFIG5L,
;	__CONFIG	_CONFIG5H,
; 	__CONFIG	_CONFIG6L,
; 	__CONFIG	_CONFIG6H,
;	__CONFIG	_CONFIG7L,
;	__CONFIG	_CONFIG7H,



	end
   
